<h3>Liste des articles</h3>
<table>
    <thead>
    <tr>
        <th>Id</th>
        <th>Titre</th>
        <th>Description</th>
    </tr>
    </thead>
    <tbody>
    <?php
    /** @var Article $post */
    foreach ($posts as $post):
        ?>
        <tr>
            <td><?= $post->getId(); ?></td>
            <td><a href="post-detail?id=<?= $post->getId(); ?>"><?= $post->getTitle(); ?></a></td>
            <td><?= $post->getDescription() ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>