<!DOCTYPE html>
<html>
<!--VUES-->
<head>
    <meta charset="utf-8">
    <title>Liste des articles</title>
    <link rel="stylesheet" href="app.css">
</head>
<body>
<h3>Liste des articles</h3>
<table>
    <thead>
    <tr>
        <th>Id</th>
        <th>Titre</th>
        <th>Description</th>
    </tr>
    </thead>
    <tbody>
    <?php
    /** @var Article $post */
    foreach ($posts as $post):
        ?>
        <tr>
            <td><?= $post->getId(); ?></td>
            <td><?= $post->getTitle(); ?></td>
            <td><?= $post->getDescription() ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

</body>
</html>